[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
"@openzeppelin-contracts-upgradeable" = "5.0.2"
"@openzeppelin-contracts" = "5.0.2"
"@uniswap-v2-core" = "1.0.1"

